name = "ANNEX3.0"
author = "donabe"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e78e0fe9e3cf502b5095d485f134a2b15ccdd0fd7ab2b9940d4f097d93484282"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.251"
