name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a711a33f6e3f1cd01c23f9b766916d270af5e8fe47b70fbf4241815ee697351"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
