name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdd9151239dccca9f10b8a98e788e2f2175f2998847c0ec2184599c822e77d6c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
