name = "donabeya"
author = "donabe8898"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5b384f4ae99d6500eede7fde82f46a43e1a1f7ee514fd0f8227e2d301aa5c7a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
